name: Build
on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mode:
          - std
          - startup
        lang:
          - sc
          - tc
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'

      - uses: actions/setup-go@v3
        with:
          go-version-file: 'go.mod'

      - name: install spruce
        run: |
          id
          wget -nv https://github.com/geofffranks/spruce/releases/download/v1.31.1/spruce-linux-amd64
          chmod a+x spruce-linux-amd64
          mv spruce-linux-amd64 ~/go/bin/spruce

      - uses: ConorMacBride/install-package@v1
        with:
          apt: textql jq

      - name: build
        env:
          MODE: ${{ matrix.mode }}
          LANG: ${{ matrix.lang }}
        run: |
          make gen
          make build MODE=$MODE LANG_TYPE=$LANG
          echo "VERSION=$(git describe --tags)" >> $GITHUB_ENV

      - name: publish
        env:
          MODE: ${{ matrix.mode }}
          LANG: ${{ matrix.lang }}
        run: |
          make publish MODE=$MODE LANG_TYPE=$LANG
          mkdir -p build/mods/wing
          cp -r wing.mpq build/mods/wing
          cd build
          zip -r wing-$MODE-$LANG-$VERSION.zip mods

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: build/wing-*.zip
          name: wing-${{ matrix.mode }}-${{ matrix.lang }}-${{ env.VERSION }}.zip
          if-no-files-found: error

  publish:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          path: './'
      - name: List files
        run: ls -lhR
      - name: Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: true
          files: |
            */wing-*.zip

